### ISSUE TITLE
[Feature] Make Longship a BepInEx mod

### ISSUE THREAD

**Issue by AlexMog** [AlexMog/Longship#10]
Currently, Longship uses UnityDoorstop as an injection mechanism, which seems not to be used by many mods in the community.
BepInEx (https://github.com/BepInEx/BepInEx) is used by most of the community (at least on this website: https://valheim.thunderstore.io/) which pushes me to provide Longship on BepInEx instead of UnityDoorstop to provide a simpler way for users to have multiple mods using BepInEx including Longship.

**Comment by AtroposOrbis** [comment]
Yeah this is extremely important for mass adoption of your mod here.

**Comment by Hi-ImKyle** [comment]
I second this, everyone modding the game should be using BepInEx, much like RoR2. It shouldn't be that hard to implement :+1:
