### ISSUE TITLE
TLS Failure on launch

### ISSUE THREAD

**Issue by mbround18** [AlexMog/Longship#14]
![image](https://user-images.githubusercontent.com/12646562/108622257-60e49000-73ec-11eb-8f40-f704709957ba.png)

New server, new installation, using ValheimPlus and Longship gets the error above on launch

**Comment by AlexMog** [comment]
Hello,
Thanks for your bug report !
This error will not affect Longship nor ValheimPlus, it's an error because Longship is not able to check for updates :), I will fix it soon !

**Comment by AtroposOrbis** [comment]
@mbround18 & @AlexMog my dreams are coming true <3

**Comment by AlexMog** [comment]
This should be fixed with the shift to BepInEx.
