### ISSUE TITLE
0.1.5 No longer allowes servers without password

### ISSUE THREAD

**Issue by oswaldo-grassiotto** [AlexMog/Longship#20]
0.1 allowed me to disable password, after upgrading to 0.1.5 server throws a "password is too short" error during startup and shuts down.

**Comment by AlexMog** [comment]
Hello,
Thanks for your bug report.
I'll fix that on the next patch !

**Comment by zuffdaddy** [comment]
For me it's warning the password is too short. Are there new password requirements?

**Comment by AlexMog** [comment]
The passwort should be at least 6 characters (it's the default check that does Valheim)

**Comment by frazierzak** [comment]
> 
> 
> The passwort should be at least 6 characters (it's the default check that does Valheim)

I had deleted my response before you replied, but I had forgot to configure the longship.cfg. Fixed now. Thanks!

**Comment by AlexMog** [comment]
Fixed in last release
