### ISSUE TITLE
Feature request: ward stone improvement.

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [AlexMog/Longship#23]
Hi,
if and when you have time, would you consider looking into the ward stone mechanics and make it something like "players other than authorized cannot dismantle at a distance" and "when authorized players are not online everything is indestructible, for 3 days then decay kicks in"?
Make sense? to make the ward stone a land claim block and a offline griefing protection.

**Comment by Hi-ImKyle** [comment]
This might be something a Longship plugin could do eventually instead of a direct feature maybe?

**Comment by AlexMog** [comment]
Yep, it's not the features that will be developed in Longship !

**Comment by Uber-God** [comment]
are you interested in my project? open market ----> stock market?

https://discord.gg/t6hVbbvx
